"""Pre-specified analyses (paper/analysis_plan.md). Reads data/dataset/papers.csv, data/refs/*.verified.json,
data/adjudication/decisions.csv (manual adjudications) and writes paper/results_tables.md + data/dataset/papers_final.csv."""
import json, glob, os, re, math
import numpy as np, pandas as pd
from scipy import stats

def wilson(k, n, z=1.96):
    if n == 0: return (float('nan'), float('nan'), float('nan'))
    p = k / n; d = 1 + z*z/n; c = p + z*z/(2*n); h = z*math.sqrt(p*(1-p)/n + z*z/(4*n*n))
    return (p, (c-h)/d, (c+h)/d)

def fmt_pct(k, n):
    p, lo, hi = wilson(k, n); return f"{100*p:.1f}% ({k}/{n}; 95% CI {100*lo:.1f}-{100*hi:.1f})"

def load_refs():
    rows = []
    for f in sorted(glob.glob('data/refs/*.verified.json')):
        m = re.match(r'^(\d+)_([A-Za-z0-9_-]+)\.verified\.json$', os.path.basename(f))
        if not m: continue
        d = json.load(open(f))
        if not isinstance(d, dict): continue
        for e in d.get('entries', []):
            rows.append({'number': int(m.group(1)), 'forum_id': m.group(2), 'idx': e['idx'], 'junk': bool(e.get('junk')), 'verdict': e['verdict'], 'via': e.get('via'),
                         'title': e.get('title'), 'year': e.get('year'), 'doi': e.get('doi'), 'arxiv': e.get('arxiv'), 'has_url': bool(e.get('urls')), 'second_pass_hit': bool(e.get('second_pass_hit'))})
    return pd.DataFrame(rows)

def main():
    papers = pd.read_csv('data/dataset/papers.csv')
    refs = load_refs()
    dec_path = 'data/adjudication/decisions.csv'
    dec = pd.read_csv(dec_path) if os.path.exists(dec_path) else pd.DataFrame(columns=['number', 'idx', 'category'])
    # consistency: a decision only applies if the entry it was made for still has the same (normalised) title after any re-parse
    import unidecode
    def _n(x): return re.sub(r'[^a-z0-9]+', ' ', unidecode.unidecode(str(x or '')).lower()).strip()
    dec = dec.rename(columns={'title': 'dec_title'})
    refs = refs.merge(dec[['number', 'idx', 'category', 'dec_title', 'note']], on=['number', 'idx'], how='left')
    mism = refs[refs.category.notna() & refs.dec_title.notna() & refs.title.notna() & (refs.apply(lambda r: _n(r.dec_title) != _n(r.title), axis=1))]
    if len(mism):
        print(f'WARNING: {len(mism)} decisions no longer match their entry title after re-parse; ignoring them:', mism[['number','idx']].values.tolist()[:20])
        refs.loc[mism.index, 'category'] = None
    refs['corrupt_tags'] = refs.note.fillna('').str.findall(r'\[(title|authors|identifier|venue|year)\]').apply(lambda l: ','.join(sorted(set(l))) if isinstance(l, list) else '')
    ok = refs[~refs.junk].copy()
    # a manual decision (made with the full entry text and a web search) takes precedence over an automated verdict;
    # automated VERIFIED applies only to entries without a decision
    ok['status'] = np.where(ok.category.isin(['EXISTS', 'WEB_RESOURCE_EXISTS']), 'EXISTS',
                   np.where(ok.category.isin(['EXISTS_CORRUPTED']), 'EXISTS_CORRUPTED',
                   np.where(ok.category.isin(['NOT_FOUND', 'WEB_RESOURCE_NOT_FOUND']), 'NOT_FOUND',
                   np.where(ok.category.isin(['UNADJUDICABLE']), 'UNADJUDICABLE',
                   np.where(ok.category.isin(['PLACEHOLDER']), 'PLACEHOLDER',
                   np.where(ok.verdict.isin(['VERIFIED', 'VERIFIED_URL']), 'VERIFIED', 'PENDING'))))))
    ok['fabricated'] = ok.status.isin(['NOT_FOUND', 'EXISTS_CORRUPTED'])
    ok['defective'] = ok.status.isin(['NOT_FOUND', 'EXISTS_CORRUPTED', 'PLACEHOLDER'])
    ok['adjudicated'] = ~ok.status.isin(['PENDING'])
    L = []
    L.append('# Results tables (auto-generated by code/analysis.py)' + (' [human-overridden blind labels]' if os.environ.get('BLIND_ESTIMATE') else '') + '\n')
    L.append(f"Papers with parsed references: {ok.number.nunique()}; references (non-junk): {len(ok)}; automated verified: {int((ok.status=='VERIFIED').sum())}; pending adjudication: {int((ok.status=='PENDING').sum())}\n")
    L.append('## Reference-level status\n'); L.append(ok.status.value_counts().to_frame('n').to_markdown()); L.append('')
    n_ext = len(ok); n_auto = int((ok.status == 'VERIFIED').sum()); n_man = n_ext - n_auto; n_un = int((ok.status == 'UNADJUDICABLE').sum())
    L.append('## Flow of references\n'); L.append('| Step | n |\n|:--|--:|\n' + f'| Extracted non-junk entries | {n_ext} |\n| Verified automatically (no manual decision) | {n_auto} |\n| Manually adjudicated | {n_man} |\n| of which UNADJUDICABLE (excluded) | {n_un} |\n| Analysed (adjudicable) | {n_ext - n_un} |\n')
    # per paper (exclude UNADJUDICABLE from denominators; treat PENDING as not fabricated but report count)
    denom = ok[ok.status != 'UNADJUDICABLE']
    per = denom.groupby(['number', 'forum_id']).agg(n_refs=('idx', 'size'), n_fab=('fabricated', 'sum'), n_defective=('defective', 'sum'), n_placeholder=('status', lambda s: (s=='PLACEHOLDER').sum()), n_notfound=('status', lambda s: (s=='NOT_FOUND').sum()),
                                                   n_corrupt=('status', lambda s: (s=='EXISTS_CORRUPTED').sum()), n_pending=('status', lambda s: (s=='PENDING').sum())).reset_index()
    nv = denom[denom.status == 'VERIFIED'].groupby(['number', 'forum_id']).size().rename('n_verified').reset_index()
    per = per.merge(nv, on=['number', 'forum_id'], how='left').fillna({'n_verified': 0})
    per['share_fab'] = per.n_fab / per.n_refs
    per['share_nf'] = per.n_notfound / per.n_refs
    per['share_defective'] = per.n_defective / per.n_refs
    df = papers.merge(per, on=['number', 'forum_id'], how='left')
    if not os.environ.get('BLIND_ESTIMATE'): df.to_csv('data/dataset/papers_final.csv', index=False)
    have = df[df.n_refs.notna()].copy()
    have['any_fab'] = have.n_fab > 0
    L.append('## Q1 Prevalence by outcome group (papers with references; pending entries counted as not fabricated)\n')
    g = have.groupby('group').apply(lambda x: pd.Series({'papers': len(x), 'refs': int(x.n_refs.sum()), 'fabricated_refs': int(x.n_fab.sum()),
        'ref_level_share': f"{100*x.n_fab.sum()/x.n_refs.sum():.1f}%", 'papers_with_>=1': fmt_pct(int(x.any_fab.sum()), len(x)), 'median_share': f"{100*x.share_fab.median():.1f}%", 'pending_refs': int(x.n_pending.sum())}))
    L.append(g.to_markdown()); L.append('')
    rev = have[have.group.isin(['Conference', 'Rejected_Submission'])]
    L.append(f"Reviewed papers (accepted+rejected): papers with >=1 fabricated reference: {fmt_pct(int(rev.any_fab.sum()), len(rev))}; reference-level: {fmt_pct(int(rev.n_fab.sum()), int(rev.n_refs.sum()))}\n")
    # Q2 organizer flag
    of_path = 'data/adjudication/organizer_flags.csv'
    if os.path.exists(of_path):
        of = pd.read_csv(of_path).merge(ok[['number', 'idx', 'status']], left_on=['number', 'matched_idx'], right_on=['number', 'idx'], how='left')
        m = of[of.matched_idx.notna() & of.status.notna() & (of.status != 'PENDING')]
        L.append('## Q2a Precision of the organizers\' flagged examples (matched to our entries, adjudicated)\n')
        L.append(m.status.value_counts().to_frame('n').to_markdown())
        if len(m): L.append(f"\nFlagged examples that are fabricated (NOT_FOUND or EXISTS_CORRUPTED): {fmt_pct(int(m.status.isin(['NOT_FOUND','EXISTS_CORRUPTED']).sum()), len(m))}; that exist as cited: {fmt_pct(int(m.status.isin(['VERIFIED','EXISTS']).sum()), len(m))}\n")
        chk = rev[rev.related_work_check == True].copy()
        chk['org_flag'] = chk.rw_n_examples.fillna(0) > 0
        if len(chk):
            tp = int((chk.org_flag & chk.any_fab).sum()); fn = int((~chk.org_flag & chk.any_fab).sum()); fp = int((chk.org_flag & ~chk.any_fab).sum()); tn = int((~chk.org_flag & ~chk.any_fab).sum())
            po = (tp+tn)/len(chk); pe = ((tp+fp)*(tp+fn) + (fn+tn)*(fp+tn))/len(chk)**2; kappa = (po-pe)/(1-pe) if pe < 1 else float('nan')
            L.append(f"## Q2b Paper-level agreement, organizer flag vs. audit (>=1 fabricated), reviewed papers with a check (n={len(chk)})\n")
            L.append(f"TP={tp} FP={fp} FN={fn} TN={tn}; sensitivity={tp/(tp+fn) if tp+fn else float('nan'):.2f}; specificity={tn/(tn+fp) if tn+fp else float('nan'):.2f}; kappa={kappa:.2f}\n")
    # Q3 autonomy
    L.append('## Q3 Fabrication vs self-reported autonomy in writing (reviewed papers)\n')
    w = rev[rev.writing.isin(list('ABCD'))]
    if len(w):
        t = w.groupby('writing').apply(lambda x: pd.Series({'papers': len(x), 'mean_share_fab': f"{100*x.share_fab.mean():.1f}%", 'papers_with_>=1': fmt_pct(int(x.any_fab.sum()), len(x))}))
        L.append(t.to_markdown())
        if w.writing.nunique() > 1:
            kw = stats.kruskal(*[x.share_fab.values for _, x in w.groupby('writing')])
            L.append(f"\nKruskal-Wallis across writing tiers: H={kw.statistic:.2f}, p={kw.pvalue:.3f}\n")
        stages = ['hypothesis_development', 'experimental_design', 'data_analysis', 'writing']
        w2 = w.copy()
        w2['auton'] = w2[stages].apply(lambda r: sum('ABCD'.index(v)+1 for v in r) if all(isinstance(v, str) and v in 'ABCD' for v in r) else np.nan, axis=1)
        w2 = w2.dropna(subset=['auton'])
        if len(w2) > 5:
            rho = stats.spearmanr(w2.auton, w2.share_fab)
            L.append(f"Spearman(overall autonomy score 4-16, fabricated share) = {rho.statistic:.3f} (p={rho.pvalue:.3f}, n={len(w2)})\n")
    # Q4 review outcomes
    L.append('## Q4 Fabrication vs review scores and acceptance (reviewed papers)\n')
    for col, name in [('airev1', 'GPT-5 (AIRev1)'), ('airev2', 'Gemini 2.5 Pro (AIRev2)'), ('airev3', 'Claude Sonnet 4 (AIRev3)'), ('human_score', 'Human expert')]:
        s = rev.dropna(subset=[col])
        if len(s) > 5:
            rho = stats.spearmanr(s[col], s.share_fab)
            L.append(f"- {name}: Spearman rho={rho.statistic:.3f} (p={rho.pvalue:.3f}, n={len(s)}); mean score, papers with vs without fabricated refs: {s[s.any_fab][col].mean():.2f} vs {s[~s.any_fab][col].mean():.2f}")
    acc_with = rev[rev.any_fab].group.eq('Conference'); acc_without = rev[~rev.any_fab].group.eq('Conference')
    L.append(f"- Acceptance rate: papers with >=1 fabricated ref {fmt_pct(int(acc_with.sum()), len(acc_with))} vs without {fmt_pct(int(acc_without.sum()), len(acc_without))}")
    tbl = [[int(acc_with.sum()), int((~acc_with).sum())], [int(acc_without.sum()), int((~acc_without).sum())]]
    fe = stats.fisher_exact(tbl)
    L.append(f"- Fisher exact test (accepted x any fabricated): odds ratio={fe[0]:.2f}, p={fe[1]:.4f}; table [[acc&fab, rej&fab],[acc&clean, rej&clean]]={tbl}")
    mean_llm_all = rev[['airev1', 'airev2', 'airev3']].mean(axis=1)
    rho_m = stats.spearmanr(mean_llm_all, rev.share_fab)
    L.append(f"- Mean LLM score vs fabricated share: Spearman rho={rho_m.statistic:.3f} (p={rho_m.pvalue:.3f}, n={len(rev)})")
    try:
        import statsmodels.api as sm
    except ImportError:
        sm = None
    if sm is not None:
        X = rev[['share_fab']].copy(); X['mean_llm'] = rev[['airev1', 'airev2', 'airev3']].mean(axis=1); X = sm.add_constant(X.fillna(X.mean()))
        y = (rev.group == 'Conference').astype(int)
        try:
            if int(acc_with.sum()) == 0 or int(acc_without.sum()) == 0:
                L.append("- Logistic regression not fitted: complete separation (no accepted paper in one of the groups); see Fisher exact test above")
            else:
                res = sm.Logit(y, X).fit(disp=0)
                L.append(f"- Logistic regression accepted ~ share_fab + mean LLM score: coef(share_fab)={res.params['share_fab']:.2f} (p={res.pvalues['share_fab']:.3f}), coef(mean_llm)={res.params['mean_llm']:.2f} (p={res.pvalues['mean_llm']:.3g}), n={len(y)}")
                ci = res.conf_int(); L.append(f"- Logistic diagnostics: converged={res.mle_retvals.get('converged')}, iterations={res.mle_retvals.get('iterations')}; SE(share_fab)={res.bse['share_fab']:.2f}, 95% CI [{ci.loc['share_fab',0]:.1f}, {ci.loc['share_fab',1]:.1f}]; SE(mean_llm)={res.bse['mean_llm']:.2f}; no accepted paper above a fabricated share of 10% (quasi-separation in the tail)")
                Xi = X.copy(); Xi['share_fab'] = (rev.share_fab > 0.10).astype(int).values
                try:
                    ri = sm.Logit(y, Xi).fit(disp=0); L.append(f"- Indicator model accepted ~ (share_fab > 10%) + mean LLM score: coef={ri.params['share_fab']:.2f} (SE {ri.bse['share_fab']:.2f}, p={ri.pvalues['share_fab']:.3g}); converged={ri.mle_retvals.get('converged')}")
                except Exception as e2: L.append(f"- Indicator model not fitted (separation): {e2}")
                Xb = X.copy(); Xb['share_fab'] = rev.any_fab.astype(int).values
                rb = sm.Logit(y, Xb).fit(disp=0); cb = rb.conf_int(); L.append(f"- Binary model accepted ~ any_fab + mean LLM score: coef(any_fab)={rb.params['share_fab']:.2f} (SE {rb.bse['share_fab']:.2f}, 95% CI [{cb.loc['share_fab',0]:.2f}, {cb.loc['share_fab',1]:.2f}], p={rb.pvalues['share_fab']:.3g}); odds ratio {np.exp(rb.params['share_fab']):.2f}")
        except Exception as e:
            L.append(f"- Logistic regression failed: {e}")
    L.append('')
    # Q1b adjusted for undetected corruption among automatically verified entries (blind check, code/blind_checks.py)
    bj = os.environ.get('BLIND_ESTIMATE', 'data/dataset/blind_autoverified_estimate.json')
    if os.path.exists(bj):
        b = json.load(open(bj)); pop = b['population_by_source']; samp = b['sample_by_source']; N = sum(pop.values())
        rng = np.random.default_rng(20260929); draws = []
        for _ in range(4000):
            est = 0.0
            for g, cnt in samp.items():
                ng = sum(cnt.values()); kg = cnt.get('EXISTS_CORRUPTED', 0)
                est += rng.beta(kg + 0.5, ng - kg + 0.5) * pop.get(g, 0)
            draws.append(est / N)
        draws = np.array(draws); est = b['est_corrupted_share']; lo, hi = np.percentile(draws, [2.5, 97.5])
        L.append('## Q1b Reference-level prevalence adjusted for corrupted citations among automatically verified entries\n')
        L.append(f"Blind check of {b['n']} automatically verified entries: source-weighted corrupted share {100*est:.1f}% (bootstrap 95% CI {100*lo:.1f}-{100*hi:.1f}); wholly invented {100*b['est_notfound_share']:.1f}%. Applied uniformly to each paper's automatically verified entries:\n")
        for lab, sub in [('Reviewed (accepted+rejected)', rev), ('Accepted', rev[rev.group == 'Conference']), ('Rejected', rev[rev.group == 'Rejected_Submission']), ('All papers with references', have)]:
            nf, nr, nv_ = int(sub.n_fab.sum()), int(sub.n_refs.sum()), int(sub.n_verified.sum())
            adj = (nf + draws * nv_) / nr
            exp_any = float(np.mean([1.0 if a else 1 - (1 - est) ** v for a, v in zip(sub.any_fab, sub.n_verified)]))
            L.append(f"- {lab}: adjudicated fabricated share {100*nf/nr:.1f}% -> adjusted {100*(nf + est*nv_)/nr:.1f}% (95% CI {100*np.percentile(adj,2.5):.1f}-{100*np.percentile(adj,97.5):.1f}); expected share of papers with >=1 fabricated or corrupted reference {100*exp_any:.0f}% (observed {100*sub.any_fab.mean():.1f}%)")
        L.append('')
    # Q1c composition-aware adjustment: per-source rates applied to each submission's own verification-source mix
    if os.path.exists(bj):
        src_of = {'crossref': 'crossref', 's2': 's2', 'doi': 'doi', 'url': 'url'}
        def grp_via(v): v = str(v or ''); return src_of.get(v, 'arxiv' if v.startswith('arxiv') else ('url' if v == 'url' else 'other'))
        vs = ok[ok.status == 'VERIFIED'].assign(src=ok[ok.status == 'VERIFIED'].via.map(grp_via)) if 'via' in ok.columns else None
        if vs is not None:
            comp = vs.groupby(['number', 'forum_id', 'src']).size().unstack(fill_value=0).reset_index()
            for g in ['crossref', 's2', 'doi', 'arxiv', 'url', 'other']:
                if g not in comp.columns: comp[g] = 0
            hc = have.merge(comp, on=['number', 'forum_id'], how='left').fillna({g: 0 for g in ['crossref', 's2', 'doi', 'arxiv', 'url', 'other']})
            rng2 = np.random.default_rng(20261003); B = 4000
            rates = {}   # per-source posterior draws for corrupted and invented
            for g in ['crossref', 's2', 'doi', 'arxiv', 'url', 'other']:
                cnt = samp.get(g, {}); ng = sum(cnt.values()); kc = cnt.get('EXISTS_CORRUPTED', 0); kn = cnt.get('NOT_FOUND', 0)
                rates[g] = (rng2.beta(kc + 0.5, ng - kc + 0.5, B) if ng else np.zeros(B), rng2.beta(kn + 0.5, ng - kn + 0.5, B) if ng else np.zeros(B))
            L.append('## Q1c Composition-aware adjustment (per-source corruption rates applied to each submission\'s verification-source mix)\n')
            hc_rev = hc[hc.group.isin(['Conference', 'Rejected_Submission'])]
            for lab, sub in [('Reviewed', hc_rev), ('Accepted', hc_rev[hc_rev.group == 'Conference']), ('Rejected', hc_rev[hc_rev.group == 'Rejected_Submission'])]:
                nv = {g: int(sub[g].sum()) for g in rates}; nr = int(sub.n_refs.sum())
                add_c = sum(rates[g][0] * nv[g] for g in rates); add_n = sum(rates[g][1] * nv[g] for g in rates)
                adj = (int(sub.n_fab.sum()) + add_c) / nr; adj_n = (int(sub.n_notfound.sum()) + add_n) / nr
                L.append(f"- {lab}: verified by source {nv}; adjusted fabricated share {100*np.median(adj):.1f}% (95% {100*np.percentile(adj,2.5):.1f}-{100*np.percentile(adj,97.5):.1f}); adjusted invented share {100*np.median(adj_n):.1f}% ({100*np.percentile(adj_n,2.5):.1f}-{100*np.percentile(adj_n,97.5):.1f}); expected undetected invented references {np.median(add_n):.0f} (95% {np.percentile(add_n,2.5):.0f}-{np.percentile(add_n,97.5):.0f})")
            # sensitivity: accepted-paper projection without the five-entry 'other' stratum
            acc = hc_rev[hc_rev.group == 'Conference']
            nv_acc = {g: int(acc[g].sum()) for g in rates}
            add_n_all = sum(rates[g][1] * nv_acc[g] for g in rates); add_n_noother = sum(rates[g][1] * nv_acc[g] for g in rates if g != 'other')
            add_c_noother = sum(rates[g][0] * nv_acc[g] for g in rates if g != 'other')
            L.append(f"- Accepted, sensitivity: expected undetected invented references {np.median(add_n_all):.0f} ({np.percentile(add_n_all,2.5):.0f}-{np.percentile(add_n_all,97.5):.0f}) with all strata; {np.median(add_n_noother):.0f} ({np.percentile(add_n_noother,2.5):.0f}-{np.percentile(add_n_noother,97.5):.0f}) excluding the 'other' stratum ({nv_acc['other']} accepted-paper entries); adjusted invented share without 'other' {100*(int(acc.n_notfound.sum()) + add_n_noother).mean()/int(acc.n_refs.sum()) if False else 100*np.median((int(acc.n_notfound.sum()) + add_n_noother)/int(acc.n_refs.sum())):.1f}% ({100*np.percentile((int(acc.n_notfound.sum()) + add_n_noother)/int(acc.n_refs.sum()),2.5):.1f}-{100*np.percentile((int(acc.n_notfound.sum()) + add_n_noother)/int(acc.n_refs.sum()),97.5):.1f}); adjusted fabricated share without 'other' {100*np.median((int(acc.n_fab.sum()) + add_c_noother)/int(acc.n_refs.sum())):.1f}%")
            # flagged vs unflagged composition (reviewed papers with a check)
            hcc = hc_rev[hc_rev.related_work_check == True].copy(); hcc['flag'] = hcc.rw_n_examples.fillna(0) > 0
            for lab, sub in [('flagged', hcc[hcc.flag]), ('unflagged', hcc[~hcc.flag])]:
                tot = sum(int(sub[g].sum()) for g in rates); cr = int(sub['crossref'].sum())
                exp_c = sum(float(np.median(rates[g][0])) * int(sub[g].sum()) for g in rates)
                L.append(f"- {lab} submissions (n={len(sub)}): automatically verified entries {tot}, of which Crossref title matches {100*cr/max(1,tot):.1f}%; expected undetected corrupted references {exp_c:.0f} ({exp_c/max(1,len(sub)):.2f} per submission)")
            L.append('')
    # Strict identity-level definition (comparable to Russinovich et al.): NOT_FOUND plus corrupted entries whose author list is wrong
    MINOR_RX = r'given name|first name|initial|abbreviat|omitt|dropped|order|rotated|promoted|appended|added as|et al\\. only|name variant|spell'
    minor = ok.note.fillna('').str.contains(MINOR_RX, case=False, regex=True)
    ok['identity_fail'] = (ok.status == 'NOT_FOUND') | ((ok.status == 'EXISTS_CORRUPTED') & ok.corrupt_tags.str.contains('authors') & ~minor)
    n_auth = int(((ok.status == 'EXISTS_CORRUPTED') & ok.corrupt_tags.str.contains('authors')).sum()); n_minor = int(((ok.status == 'EXISTS_CORRUPTED') & ok.corrupt_tags.str.contains('authors') & minor).sum())
    idf = denom.assign(identity_fail=ok.loc[denom.index, 'identity_fail']).groupby(['number', 'forum_id']).identity_fail.sum().rename('n_identity').reset_index()
    have = have.merge(idf, on=['number', 'forum_id'], how='left').fillna({'n_identity': 0}); rev = have[have.group.isin(['Conference', 'Rejected_Submission'])]
    L.append('## Strict identity-level definition (wholly invented, or real work with a substantially wrong author list)\n')
    L.append(f"Author-list corruptions: {n_auth}; of which minor variants (given names, initials, omitted or re-ordered co-authors) excluded from the strict definition: {n_minor}\n")
    for lab, sub in [('Reviewed', rev), ('Accepted', rev[rev.group == 'Conference']), ('Rejected', rev[rev.group == 'Rejected_Submission'])]:
        L.append(f"- {lab}: references {fmt_pct(int(sub.n_identity.sum()), int(sub.n_refs.sum()))}; papers with >=1 {fmt_pct(int((sub.n_identity > 0).sum()), len(sub))}; papers with >=2 {fmt_pct(int((sub.n_identity >= 2).sum()), len(sub))}")
    L.append('')
    # Sensitivity of the headline (reviewed papers) to the PLACEHOLDER and UNADJUDICABLE classifications
    un = ok[(ok.status == 'UNADJUDICABLE')].groupby(['number', 'forum_id']).size().rename('n_unadj').reset_index()
    sens = rev.merge(un, on=['number', 'forum_id'], how='left').fillna({'n_unadj': 0})
    L.append('## Sensitivity of the reviewed-paper headline to classification choices\n')
    L.append(f"- Base (fabricated = NOT_FOUND + EXISTS_CORRUPTED; UNADJUDICABLE excluded): papers {fmt_pct(int(sens.any_fab.sum()), len(sens))}; references {fmt_pct(int(sens.n_fab.sum()), int(sens.n_refs.sum()))}")
    L.append(f"- Placeholders counted as fabricated: papers {fmt_pct(int((sens.n_defective > 0).sum()), len(sens))}; references {fmt_pct(int(sens.n_defective.sum()), int(sens.n_refs.sum()))}")
    L.append(f"- UNADJUDICABLE entries counted as fabricated: papers {fmt_pct(int(((sens.n_fab + sens.n_unadj) > 0).sum()), len(sens))}; references {fmt_pct(int((sens.n_fab + sens.n_unadj).sum()), int((sens.n_refs + sens.n_unadj).sum()))}")
    L.append(f"- UNADJUDICABLE entries counted as real: papers {fmt_pct(int(sens.any_fab.sum()), len(sens))}; references {fmt_pct(int(sens.n_fab.sum()), int((sens.n_refs + sens.n_unadj).sum()))}")
    L.append(f"- Wholly invented only: papers {fmt_pct(int((sens.n_notfound > 0).sum()), len(sens))}; references {fmt_pct(int(sens.n_notfound.sum()), int(sens.n_refs.sum()))}\n")
    # Secondary outcome: wholly invented references only (NOT_FOUND), robust to undetected corruption
    L.append('## Secondary outcome: wholly invented references only (NOT_FOUND)\n')
    rev2 = rev.copy(); rev2['any_nf'] = rev2.n_notfound > 0
    L.append(f"- Reviewed papers with >=1 wholly invented reference: {fmt_pct(int(rev2.any_nf.sum()), len(rev2))}; reference-level: {fmt_pct(int(rev2.n_notfound.sum()), int(rev2.n_refs.sum()))}")
    if len(w):
        t2 = w.copy(); t2['any_nf'] = t2.n_notfound > 0
        L.append('- By writing tier (papers with >=1 wholly invented): ' + '; '.join(f"{k}: {fmt_pct(int(x.any_nf.sum()), len(x))}" for k, x in t2.groupby('writing')))
        if w.writing.nunique() > 1:
            kw2 = stats.kruskal(*[x.share_nf.values for _, x in w.groupby('writing')]); L.append(f"- Kruskal-Wallis across writing tiers (invented share): H={kw2.statistic:.2f}, p={kw2.pvalue:.4f}")
    for col, name in [('airev1', 'GPT-5'), ('airev2', 'Gemini 2.5 Pro'), ('airev3', 'Claude Sonnet 4'), ('human_score', 'Human expert')]:
        s2 = rev2.dropna(subset=[col])
        if len(s2) > 5:
            rho = stats.spearmanr(s2[col], s2.share_nf)
            L.append(f"- {name}: Spearman rho(invented share)={rho.statistic:.3f} (p={rho.pvalue:.3f}, n={len(s2)}); mean score with vs without invented refs: {s2[s2.any_nf][col].mean():.2f} vs {s2[~s2.any_nf][col].mean():.2f}")
    a_w = rev2[rev2.any_nf].group.eq('Conference'); a_wo = rev2[~rev2.any_nf].group.eq('Conference')
    L.append(f"- Acceptance: papers with >=1 invented ref {fmt_pct(int(a_w.sum()), len(a_w))} vs without {fmt_pct(int(a_wo.sum()), len(a_wo))}")
    tbl2 = [[int(a_w.sum()), int((~a_w).sum())], [int(a_wo.sum()), int((~a_wo).sum())]]
    if all(v >= 0 for r_ in tbl2 for v in r_):
        fe2 = stats.fisher_exact(tbl2); L.append(f"- Fisher exact test (accepted x any invented): odds ratio={fe2[0]:.2f}, p={fe2[1]:.4g}; table={tbl2}")
    if sm is not None and int(a_w.sum()) > 0:
        try:
            X2 = rev2[['share_nf']].copy(); X2['mean_llm'] = rev2[['airev1', 'airev2', 'airev3']].mean(axis=1); X2 = sm.add_constant(X2.fillna(X2.mean()))
            res2 = sm.Logit((rev2.group == 'Conference').astype(int), X2).fit(disp=0)
            L.append(f"- Logistic regression accepted ~ invented share + mean LLM score: coef(share_nf)={res2.params['share_nf']:.2f} (p={res2.pvalues['share_nf']:.3g}), coef(mean_llm)={res2.params['mean_llm']:.2f}")
        except Exception as e:
            L.append(f"- Logistic regression (invented share) not fitted: {e}")
    elif int(a_w.sum()) == 0:
        L.append("- Logistic regression (invented share) not fitted: complete separation (no accepted paper has a wholly invented reference); Fisher's exact test above applies")
    L.append('')
    # Q5 reviewer detection
    rm_path = 'data/dataset/review_ref_mentions.csv'
    if os.path.exists(rm_path):
        rm = pd.read_csv(rm_path)
        det = rm.groupby('number').agg(ai_strong=('n_strong', lambda s: (s[rm.loc[s.index, 'kind']=='ai'] > 0).any()), human_strong=('n_strong', lambda s: (s[rm.loc[s.index, 'kind']=='human'] > 0).any()), ai_mention=('n_ref_sentences', lambda s: (s[rm.loc[s.index, 'kind']=='ai'] > 0).any())).reset_index()
        q5 = rev.merge(det, on='number', how='left').fillna({'ai_strong': False, 'human_strong': False, 'ai_mention': False})
        cls_path = 'data/dataset/strong_ref_statements_classified.csv'
        if os.path.exists(cls_path):  # explicit = independent assertion or echo of the authors' disclosure (vague/unrelated hits excluded)
            cls = pd.read_csv(cls_path); cls = cls[cls.kind == 'ai']
            expl = set(cls[cls['class'].isin(['explicit_independent', 'author_acknowledged'])].number.astype(int))
            indep = set(cls[cls['class'] == 'explicit_independent'].number.astype(int))
            q5['ai_strong'] = q5.number.astype(int).isin(expl); q5['ai_indep'] = q5.number.astype(int).isin(indep)
        else:
            q5['ai_indep'] = q5['ai_strong']
        fab = q5[q5.any_fab]
        L.append('## Q5 Did reviewers notice? (reviewed papers with >=1 fabricated reference)\n')
        L.append(f"- Any LLM review explicitly states references are fabricated/non-existent/unverifiable: {fmt_pct(int(fab.ai_strong.sum()), len(fab))}")
        L.append(f"- Any LLM review mentions references/citations at all: {fmt_pct(int(fab.ai_mention.sum()), len(fab))}")
        L.append(f"- ... of which the statement is the reviewer's own finding (not an echo of the authors' disclosure): {fmt_pct(int(fab.ai_indep.sum()), len(fab))}")
        hf = fab[fab.human_score.notna()]
        L.append(f"- Human expert review explicitly states so (papers with a human review): {fmt_pct(int(hf.human_strong.sum()), len(hf))}")
        nf = q5[~q5.any_fab]
        L.append(f"- False alarms: LLM 'strong' statements in papers without fabricated refs: {fmt_pct(int(nf.ai_strong.sum()), len(nf))}")
        L.append(f"- False alarms, independent assertions only: {fmt_pct(int(nf.ai_indep.sum()), len(nf))}\n")
    # Q6 taxonomy
    L.append('## Q6 Categories of adjudicated entries\n')
    adj = ok[ok.status.isin(['EXISTS', 'EXISTS_CORRUPTED', 'NOT_FOUND', 'UNADJUDICABLE'])]
    L.append(adj.status.value_counts().to_frame('n').to_markdown()); L.append('')
    cor = ok[ok.status == 'EXISTS_CORRUPTED']
    if len(cor):
        from collections import Counter
        tc = Counter(t for tags in cor.corrupt_tags for t in tags.split(',') if t)
        L.append(f"Corrupted attributes among EXISTS_CORRUPTED entries (n={len(cor)}): " + ', '.join(f"{k}: {v}" for k, v in tc.most_common()) + '\n')
    nfd = ok[ok.status == 'NOT_FOUND']
    if len(nfd): L.append(f"NOT_FOUND entries carrying a DOI: {int(nfd.doi.notna().sum())}; an arXiv id: {int(nfd.arxiv.notna().sum())}; a URL: {int(nfd.has_url.sum())}; cited year >= 2025: {int((nfd.year >= 2025).sum())} of {len(nfd)}\n")
    open('data/dataset/results_tables_human_override.md' if os.environ.get('BLIND_ESTIMATE') else 'paper/results_tables.md', 'w').write('\n'.join(L))
    print('\n'.join(L))

if __name__ == '__main__':
    main()
