"""Pre-specified analyses (paper/analysis_plan.md). Reads data/dataset/papers.csv, data/refs/*.verified.json,
data/adjudication/decisions.csv (manual adjudications) and writes paper/results_tables.md + data/dataset/papers_final.csv."""
import json, glob, os, re, math
import numpy as np, pandas as pd
from scipy import stats

def wilson(k, n, z=1.96):
    if n == 0: return (float('nan'), float('nan'), float('nan'))
    p = k / n; d = 1 + z*z/n; c = p + z*z/(2*n); h = z*math.sqrt(p*(1-p)/n + z*z/(4*n*n))
    return (p, (c-h)/d, (c+h)/d)

def fmt_pct(k, n):
    p, lo, hi = wilson(k, n); return f"{100*p:.1f}% ({k}/{n}; 95% CI {100*lo:.1f}-{100*hi:.1f})"

def load_refs():
    rows = []
    for f in sorted(glob.glob('data/refs/*.verified.json')):
        m = re.match(r'^(\d+)_([A-Za-z0-9_-]+)\.verified\.json$', os.path.basename(f))
        if not m: continue
        d = json.load(open(f))
        if not isinstance(d, dict): continue
        for e in d.get('entries', []):
            rows.append({'number': int(m.group(1)), 'forum_id': m.group(2), 'idx': e['idx'], 'junk': bool(e.get('junk')), 'verdict': e['verdict'], 'via': e.get('via'),
                         'title': e.get('title'), 'year': e.get('year'), 'doi': e.get('doi'), 'arxiv': e.get('arxiv'), 'has_url': bool(e.get('urls')), 'second_pass_hit': bool(e.get('second_pass_hit'))})
    return pd.DataFrame(rows)

def main():
    papers = pd.read_csv('data/dataset/papers.csv')
    refs = load_refs()
    dec_path = 'data/adjudication/decisions.csv'
    dec = pd.read_csv(dec_path) if os.path.exists(dec_path) else pd.DataFrame(columns=['number', 'idx', 'category'])
    # consistency: a decision only applies if the entry it was made for still has the same (normalised) title after any re-parse
    import unidecode
    def _n(x): return re.sub(r'[^a-z0-9]+', ' ', unidecode.unidecode(str(x or '')).lower()).strip()
    dec = dec.rename(columns={'title': 'dec_title'})
    refs = refs.merge(dec[['number', 'idx', 'category', 'dec_title', 'note']], on=['number', 'idx'], how='left')
    mism = refs[refs.category.notna() & refs.dec_title.notna() & refs.title.notna() & (refs.apply(lambda r: _n(r.dec_title) != _n(r.title), axis=1))]
    if len(mism):
        print(f'WARNING: {len(mism)} decisions no longer match their entry title after re-parse; ignoring them:', mism[['number','idx']].values.tolist()[:20])
        refs.loc[mism.index, 'category'] = None
    refs['corrupt_tags'] = refs.note.fillna('').str.findall(r'\[(title|authors|identifier|venue|year)\]').apply(lambda l: ','.join(sorted(set(l))) if isinstance(l, list) else '')
    ok = refs[~refs.junk].copy()
    # a manual decision (made with the full entry text and a web search) takes precedence over an automated verdict;
    # automated VERIFIED applies only to entries without a decision
    ok['status'] = np.where(ok.category.isin(['EXISTS', 'WEB_RESOURCE_EXISTS']), 'EXISTS',
                   np.where(ok.category.isin(['EXISTS_CORRUPTED']), 'EXISTS_CORRUPTED',
                   np.where(ok.category.isin(['NOT_FOUND', 'WEB_RESOURCE_NOT_FOUND']), 'NOT_FOUND',
                   np.where(ok.category.isin(['UNADJUDICABLE']), 'UNADJUDICABLE',
                   np.where(ok.category.isin(['PLACEHOLDER']), 'PLACEHOLDER',
                   np.where(ok.verdict.isin(['VERIFIED', 'VERIFIED_URL']), 'VERIFIED', 'PENDING'))))))
    ok['fabricated'] = ok.status.isin(['NOT_FOUND', 'EXISTS_CORRUPTED'])
    ok['defective'] = ok.status.isin(['NOT_FOUND', 'EXISTS_CORRUPTED', 'PLACEHOLDER'])
    ok['adjudicated'] = ~ok.status.isin(['PENDING'])
    L = []
    L.append('# Results tables (auto-generated by code/analysis.py)\n')
    L.append(f"Papers with parsed references: {ok.number.nunique()}; references (non-junk): {len(ok)}; automated verified: {int((ok.status=='VERIFIED').sum())}; pending adjudication: {int((ok.status=='PENDING').sum())}\n")
    L.append('## Reference-level status\n'); L.append(ok.status.value_counts().to_frame('n').to_markdown()); L.append('')
    # per paper (exclude UNADJUDICABLE from denominators; treat PENDING as not fabricated but report count)
    denom = ok[ok.status != 'UNADJUDICABLE']
    per = denom.groupby(['number', 'forum_id']).agg(n_refs=('idx', 'size'), n_fab=('fabricated', 'sum'), n_defective=('defective', 'sum'), n_placeholder=('status', lambda s: (s=='PLACEHOLDER').sum()), n_notfound=('status', lambda s: (s=='NOT_FOUND').sum()),
                                                   n_corrupt=('status', lambda s: (s=='EXISTS_CORRUPTED').sum()), n_pending=('status', lambda s: (s=='PENDING').sum())).reset_index()
    per['share_fab'] = per.n_fab / per.n_refs
    per['share_defective'] = per.n_defective / per.n_refs
    df = papers.merge(per, on=['number', 'forum_id'], how='left')
    df.to_csv('data/dataset/papers_final.csv', index=False)
    have = df[df.n_refs.notna()].copy()
    have['any_fab'] = have.n_fab > 0
    L.append('## Q1 Prevalence by outcome group (papers with references; pending entries counted as not fabricated)\n')
    g = have.groupby('group').apply(lambda x: pd.Series({'papers': len(x), 'refs': int(x.n_refs.sum()), 'fabricated_refs': int(x.n_fab.sum()),
        'ref_level_share': f"{100*x.n_fab.sum()/x.n_refs.sum():.1f}%", 'papers_with_>=1': fmt_pct(int(x.any_fab.sum()), len(x)), 'median_share': f"{100*x.share_fab.median():.1f}%", 'pending_refs': int(x.n_pending.sum())}))
    L.append(g.to_markdown()); L.append('')
    rev = have[have.group.isin(['Conference', 'Rejected_Submission'])]
    L.append(f"Reviewed papers (accepted+rejected): papers with >=1 fabricated reference: {fmt_pct(int(rev.any_fab.sum()), len(rev))}; reference-level: {fmt_pct(int(rev.n_fab.sum()), int(rev.n_refs.sum()))}\n")
    # Q2 organizer flag
    of_path = 'data/adjudication/organizer_flags.csv'
    if os.path.exists(of_path):
        of = pd.read_csv(of_path).merge(ok[['number', 'idx', 'status']], left_on=['number', 'matched_idx'], right_on=['number', 'idx'], how='left')
        m = of[of.matched_idx.notna() & of.status.notna() & (of.status != 'PENDING')]
        L.append('## Q2a Precision of the organizers\' flagged examples (matched to our entries, adjudicated)\n')
        L.append(m.status.value_counts().to_frame('n').to_markdown())
        if len(m): L.append(f"\nFlagged examples that are fabricated (NOT_FOUND or EXISTS_CORRUPTED): {fmt_pct(int(m.status.isin(['NOT_FOUND','EXISTS_CORRUPTED']).sum()), len(m))}; that exist as cited: {fmt_pct(int(m.status.isin(['VERIFIED','EXISTS']).sum()), len(m))}\n")
        chk = rev[rev.related_work_check == True].copy()
        chk['org_flag'] = chk.rw_n_examples.fillna(0) > 0
        if len(chk):
            tp = int((chk.org_flag & chk.any_fab).sum()); fn = int((~chk.org_flag & chk.any_fab).sum()); fp = int((chk.org_flag & ~chk.any_fab).sum()); tn = int((~chk.org_flag & ~chk.any_fab).sum())
            po = (tp+tn)/len(chk); pe = ((tp+fp)*(tp+fn) + (fn+tn)*(fp+tn))/len(chk)**2; kappa = (po-pe)/(1-pe) if pe < 1 else float('nan')
            L.append(f"## Q2b Paper-level agreement, organizer flag vs. audit (>=1 fabricated), reviewed papers with a check (n={len(chk)})\n")
            L.append(f"TP={tp} FP={fp} FN={fn} TN={tn}; sensitivity={tp/(tp+fn) if tp+fn else float('nan'):.2f}; specificity={tn/(tn+fp) if tn+fp else float('nan'):.2f}; kappa={kappa:.2f}\n")
    # Q3 autonomy
    L.append('## Q3 Fabrication vs self-reported autonomy in writing (reviewed papers)\n')
    w = rev[rev.writing.isin(list('ABCD'))]
    if len(w):
        t = w.groupby('writing').apply(lambda x: pd.Series({'papers': len(x), 'mean_share_fab': f"{100*x.share_fab.mean():.1f}%", 'papers_with_>=1': fmt_pct(int(x.any_fab.sum()), len(x))}))
        L.append(t.to_markdown())
        if w.writing.nunique() > 1:
            kw = stats.kruskal(*[x.share_fab.values for _, x in w.groupby('writing')])
            L.append(f"\nKruskal-Wallis across writing tiers: H={kw.statistic:.2f}, p={kw.pvalue:.3f}\n")
        stages = ['hypothesis_development', 'experimental_design', 'data_analysis', 'writing']
        w2 = w.copy()
        w2['auton'] = w2[stages].apply(lambda r: sum('ABCD'.index(v)+1 for v in r) if all(isinstance(v, str) and v in 'ABCD' for v in r) else np.nan, axis=1)
        w2 = w2.dropna(subset=['auton'])
        if len(w2) > 5:
            rho = stats.spearmanr(w2.auton, w2.share_fab)
            L.append(f"Spearman(overall autonomy score 4-16, fabricated share) = {rho.statistic:.3f} (p={rho.pvalue:.3f}, n={len(w2)})\n")
    # Q4 review outcomes
    L.append('## Q4 Fabrication vs review scores and acceptance (reviewed papers)\n')
    for col, name in [('airev1', 'GPT-5 (AIRev1)'), ('airev2', 'Gemini 2.5 Pro (AIRev2)'), ('airev3', 'Claude Sonnet 4 (AIRev3)'), ('human_score', 'Human expert')]:
        s = rev.dropna(subset=[col])
        if len(s) > 5:
            rho = stats.spearmanr(s[col], s.share_fab)
            L.append(f"- {name}: Spearman rho={rho.statistic:.3f} (p={rho.pvalue:.3f}, n={len(s)}); mean score, papers with vs without fabricated refs: {s[s.any_fab][col].mean():.2f} vs {s[~s.any_fab][col].mean():.2f}")
    acc_with = rev[rev.any_fab].group.eq('Conference'); acc_without = rev[~rev.any_fab].group.eq('Conference')
    L.append(f"- Acceptance rate: papers with >=1 fabricated ref {fmt_pct(int(acc_with.sum()), len(acc_with))} vs without {fmt_pct(int(acc_without.sum()), len(acc_without))}")
    tbl = [[int(acc_with.sum()), int((~acc_with).sum())], [int(acc_without.sum()), int((~acc_without).sum())]]
    fe = stats.fisher_exact(tbl)
    L.append(f"- Fisher exact test (accepted x any fabricated): odds ratio={fe[0]:.2f}, p={fe[1]:.4f}; table [[acc&fab, rej&fab],[acc&clean, rej&clean]]={tbl}")
    mean_llm_all = rev[['airev1', 'airev2', 'airev3']].mean(axis=1)
    rho_m = stats.spearmanr(mean_llm_all, rev.share_fab)
    L.append(f"- Mean LLM score vs fabricated share: Spearman rho={rho_m.statistic:.3f} (p={rho_m.pvalue:.3f}, n={len(rev)})")
    try:
        import statsmodels.api as sm
    except ImportError:
        sm = None
    if sm is not None:
        X = rev[['share_fab']].copy(); X['mean_llm'] = rev[['airev1', 'airev2', 'airev3']].mean(axis=1); X = sm.add_constant(X.fillna(X.mean()))
        y = (rev.group == 'Conference').astype(int)
        try:
            if int(acc_with.sum()) == 0 or int(acc_without.sum()) == 0:
                L.append("- Logistic regression not fitted: complete separation (no accepted paper in one of the groups); see Fisher exact test above")
            else:
                res = sm.Logit(y, X).fit(disp=0)
                L.append(f"- Logistic regression accepted ~ share_fab + mean LLM score: coef(share_fab)={res.params['share_fab']:.2f} (p={res.pvalues['share_fab']:.3f}), coef(mean_llm)={res.params['mean_llm']:.2f} (p={res.pvalues['mean_llm']:.3g}), n={len(y)}")
        except Exception as e:
            L.append(f"- Logistic regression failed: {e}")
    L.append('')
    # Q5 reviewer detection
    rm_path = 'data/dataset/review_ref_mentions.csv'
    if os.path.exists(rm_path):
        rm = pd.read_csv(rm_path)
        det = rm.groupby('number').agg(ai_strong=('n_strong', lambda s: (s[rm.loc[s.index, 'kind']=='ai'] > 0).any()), human_strong=('n_strong', lambda s: (s[rm.loc[s.index, 'kind']=='human'] > 0).any()), ai_mention=('n_ref_sentences', lambda s: (s[rm.loc[s.index, 'kind']=='ai'] > 0).any())).reset_index()
        q5 = rev.merge(det, on='number', how='left').fillna({'ai_strong': False, 'human_strong': False, 'ai_mention': False})
        cls_path = 'data/dataset/strong_ref_statements_classified.csv'
        if os.path.exists(cls_path):  # explicit = independent assertion or echo of the authors' disclosure (vague/unrelated hits excluded)
            cls = pd.read_csv(cls_path); cls = cls[cls.kind == 'ai']
            expl = set(cls[cls['class'].isin(['explicit_independent', 'author_acknowledged'])].number.astype(int))
            indep = set(cls[cls['class'] == 'explicit_independent'].number.astype(int))
            q5['ai_strong'] = q5.number.astype(int).isin(expl); q5['ai_indep'] = q5.number.astype(int).isin(indep)
        else:
            q5['ai_indep'] = q5['ai_strong']
        fab = q5[q5.any_fab]
        L.append('## Q5 Did reviewers notice? (reviewed papers with >=1 fabricated reference)\n')
        L.append(f"- Any LLM review explicitly states references are fabricated/non-existent/unverifiable: {fmt_pct(int(fab.ai_strong.sum()), len(fab))}")
        L.append(f"- Any LLM review mentions references/citations at all: {fmt_pct(int(fab.ai_mention.sum()), len(fab))}")
        L.append(f"- ... of which the statement is the reviewer's own finding (not an echo of the authors' disclosure): {fmt_pct(int(fab.ai_indep.sum()), len(fab))}")
        hf = fab[fab.human_score.notna()]
        L.append(f"- Human expert review explicitly states so (papers with a human review): {fmt_pct(int(hf.human_strong.sum()), len(hf))}")
        nf = q5[~q5.any_fab]
        L.append(f"- False alarms: LLM 'strong' statements in papers without fabricated refs: {fmt_pct(int(nf.ai_strong.sum()), len(nf))}")
        L.append(f"- False alarms, independent assertions only: {fmt_pct(int(nf.ai_indep.sum()), len(nf))}\n")
    # Q6 taxonomy
    L.append('## Q6 Categories of adjudicated entries\n')
    adj = ok[ok.status.isin(['EXISTS', 'EXISTS_CORRUPTED', 'NOT_FOUND', 'UNADJUDICABLE'])]
    L.append(adj.status.value_counts().to_frame('n').to_markdown()); L.append('')
    cor = ok[ok.status == 'EXISTS_CORRUPTED']
    if len(cor):
        from collections import Counter
        tc = Counter(t for tags in cor.corrupt_tags for t in tags.split(',') if t)
        L.append(f"Corrupted attributes among EXISTS_CORRUPTED entries (n={len(cor)}): " + ', '.join(f"{k}: {v}" for k, v in tc.most_common()) + '\n')
    nfd = ok[ok.status == 'NOT_FOUND']
    if len(nfd): L.append(f"NOT_FOUND entries carrying a DOI: {int(nfd.doi.notna().sum())}; an arXiv id: {int(nfd.arxiv.notna().sum())}; a URL: {int(nfd.has_url.sum())}; cited year >= 2025: {int((nfd.year >= 2025).sum())} of {len(nfd)}\n")
    open('paper/results_tables.md', 'w').write('\n'.join(L))
    print('\n'.join(L))

if __name__ == '__main__':
    main()
