"""Blind re-adjudication checks (responses to review): (a) agreement between a blind second adjudicator and the first
adjudicator on a stratified sample of manual decisions; (b) corruption/fabrication rate among automatically VERIFIED
entries from blind samples, weighted by verification source. Reads the sample/decision files from the job tmp dir
(copied into data/adjudication/blind/ for release) and writes data/dataset/blind_checks.md."""
import csv, glob, json, math, os, sys, collections
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
TMP = os.environ.get('BLIND_DIR', os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'data', 'adjudication', 'blind'))   # released blind samples and decisions
REL = os.path.join(ROOT, 'data', 'adjudication', 'blind'); os.makedirs(REL, exist_ok=True)
def wilson(k, n, z=1.96):
    if n == 0: return (float('nan'),) * 3
    p = k / n; d = 1 + z * z / n; c = p + z * z / (2 * n); h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)); return p, (c - h) / d, (c + h) / d
def fmt(k, n): p, lo, hi = wilson(k, n); return f"{100*p:.1f}% ({k}/{n}; 95% CI {100*lo:.1f}-{100*hi:.1f})"
def collapse(c):
    return {'WEB_RESOURCE_EXISTS': 'EXISTS', 'WEB_RESOURCE_NOT_FOUND': 'NOT_FOUND'}.get(c, c)
def kappa(pairs):
    n = len(pairs); cats = sorted({a for a, _ in pairs} | {b for _, b in pairs})
    po = sum(1 for a, b in pairs if a == b) / n
    pe = sum((sum(1 for a, _ in pairs if a == c) / n) * (sum(1 for _, b in pairs if b == c) / n) for c in cats)
    return po, (po - pe) / (1 - pe) if pe < 1 else float('nan')
L = ['# Blind re-adjudication checks (auto-generated by code/blind_checks.py)\n']
dec = {(r['number'], int(r['idx'])): r for r in csv.DictReader(open(os.path.join(ROOT, 'data', 'adjudication', 'decisions.csv')))}
retired = {}
rp = os.path.join(ROOT, 'data', 'adjudication', 'retired_decisions.csv')
if os.path.exists(rp): retired = {(r['number'], int(r['idx'])): r for r in csv.DictReader(open(rp))}
import re, unidecode
def norm(x): return re.sub(r'[^a-z0-9]+', ' ', unidecode.unidecode(str(x or '')).lower()).strip()
cur_idx = {}   # (number, normalised raw) -> current idx, so entries re-indexed by a later parse are found by text
for f in glob.glob(os.path.join(ROOT, 'data', 'refs', '*.verified.json')):
    num = os.path.basename(f).split('_')[0]
    for e in json.load(open(f))['entries']: cur_idx[(num, norm(e['raw']))] = e['idx']
# (a) manual-decision sample
pairs, pairs_fab, rows, pairs_b = [], [], [], []
for s_, d_ in [('blind_sample.json', 'blind_decisions.json'), ('blind_sample4.json', 'blind_decisions4.json')]:
    sp, dp = os.path.join(TMP, s_), os.path.join(TMP, d_)
    if not (os.path.exists(sp) and os.path.exists(dp)): continue
    sample = {o['id']: o for o in json.load(open(sp))}; blind = {d['id']: d for d in json.load(open(dp))}
    for i, o in sample.items():
        if i not in blind: continue
        n, idx = o['key'].split(':'); first = dec.get((n, cur_idx.get((n, norm(o['raw'])), int(idx)))) or retired.get((n, int(idx)))
        if not first: continue   # entry re-parsed away
        a, b = collapse(first['category']), collapse(blind[i]['category'])
        pairs.append((a, b)); fa, fb = a in ('NOT_FOUND', 'EXISTS_CORRUPTED'), b in ('NOT_FOUND', 'EXISTS_CORRUPTED'); pairs_fab.append((fa, fb))
        if s_ == 'blind_sample4.json': pairs_b.append((a, b))
        rows.append({'id': i, 'sample': s_.replace('.json', ''), 'key': o['key'], 'first': a, 'blind': b, 'blind_note': blind[i].get('note', '')[:200]})
if pairs:
    po, k = kappa(pairs); po2, k2 = kappa(pairs_fab)
    conf = collections.Counter(pairs)
    L.append(f"## (a) Blind second adjudication of {len(pairs)} sampled manual decisions (sample 1: 30 NOT_FOUND / 30 EXISTS_CORRUPTED / 30 EXISTS; sample 2: 35 EXISTS_CORRUPTED / 25 EXISTS boundary cases)\n")
    L.append(f"- Category agreement (EXISTS, EXISTS_CORRUPTED, NOT_FOUND, PLACEHOLDER, UNADJUDICABLE): {100*po:.1f}%, Cohen's kappa = {k:.2f}")
    L.append(f"- Binary agreement (fabricated = NOT_FOUND or EXISTS_CORRUPTED vs not): {100*po2:.1f}%, kappa = {k2:.2f}")
    if pairs_b:
        pob, kb = kappa(pairs_b); pob2, kb2 = kappa([(a in ('NOT_FOUND', 'EXISTS_CORRUPTED'), b in ('NOT_FOUND', 'EXISTS_CORRUPTED')) for a, b in pairs_b])
        L.append(f"- Boundary sample only (n={len(pairs_b)}): category agreement {100*pob:.1f}% (kappa {kb:.2f}); fabricated-vs-not agreement {100*pob2:.1f}% (kappa {kb2:.2f})")
    L.append("- Confusion (first adjudicator -> blind): " + '; '.join(f"{a}->{b}: {c}" for (a, b), c in sorted(conf.items())) + '\n')
    with open(os.path.join(REL, 'blind_manual_sample.csv'), 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
# (b) auto-verified samples
ent = {}
for f in glob.glob(os.path.join(ROOT, 'data', 'refs', '*.verified.json')):
    num = os.path.basename(f).split('_')[0]
    for i, e in enumerate(json.load(open(f))['entries'], 1): ent[(num, i)] = e
def grp(via): via = str(via or ''); return {'crossref': 'crossref', 's2': 's2', 'doi': 'doi'}.get(via, 'arxiv' if via.startswith('arxiv') else ('url' if via == 'url' else 'other'))
pop = collections.Counter(grp(e.get('via')) for (n, i), e in ent.items() if not e.get('junk') and e.get('verdict') in ('VERIFIED', 'VERIFIED_URL') and (n, i) not in dec)
HUMAN = json.load(open(os.path.join(REL, 'human_overrides.json'))) if os.path.exists(os.path.join(REL, 'human_overrides.json')) else {}
tab = collections.defaultdict(collections.Counter); rows = []; n_used = 0
SUFFIX = '_human' if os.environ.get('HUMAN_OVERRIDE') else ''
for s, d in [('blind_sample2.json', 'blind_decisions2.json'), ('blind_sample3.json', 'blind_decisions3.json')]:
    sp, dp = os.path.join(TMP, s), os.path.join(TMP, d)
    if not (os.path.exists(sp) and os.path.exists(dp)): continue
    sample = {o['id']: o for o in json.load(open(sp))}; blind = {x['id']: x for x in json.load(open(dp))}
    for i, o in sample.items():
        if i not in blind: continue
        n, idx = o['key'].split(':'); e = ent.get((n, cur_idx.get((n, norm(o['raw'])), int(idx))))
        if not e or e.get('verdict') not in ('VERIFIED', 'VERIFIED_URL'): continue   # re-parsed away or no longer auto-verified
        lab = blind[i]['category']
        if os.environ.get('HUMAN_OVERRIDE') and o['key'] in HUMAN: lab = HUMAN[o['key']]   # human label replaces the blind label where coded
        g = grp(e.get('via')); c = collapse(lab); tab[g][c] += 1; n_used += 1
        rows.append({'id': i, 'key': o['key'], 'via': e.get('via'), 'blind': c, 'blind_note': blind[i].get('note', '')[:200]})
if n_used:
    N = sum(pop.values()); est_c = est_nf = 0.0; parts = []
    for g in sorted(pop):
        c = tab.get(g, collections.Counter()); n = sum(c.values())
        if n: est_c += c['EXISTS_CORRUPTED'] / n * pop[g]; est_nf += c['NOT_FOUND'] / n * pop[g]
        parts.append(f"{g}: {c['EXISTS_CORRUPTED']}/{n} corrupted, {c['NOT_FOUND']}/{n} not found (population {pop[g]})")
    tot_c = sum(c['EXISTS_CORRUPTED'] for c in tab.values()); tot_nf = sum(c['NOT_FOUND'] for c in tab.values())
    L.append(f"## (b) Blind adjudication of {n_used} automatically verified entries (stratified by verification source)\n")
    L.append(f"- Corrupted citations of real works among auto-verified entries: crude {fmt(tot_c, n_used)}; source-weighted estimate {100*est_c/N:.1f}% (~{est_c:.0f} of {N})")
    L.append(f"- Wholly invented among auto-verified entries: {fmt(tot_nf, n_used)}; source-weighted {100*est_nf/N:.1f}%")
    L.append('- By source: ' + '; '.join(parts) + '\n')
    with open(os.path.join(REL, 'blind_autoverified_sample' + SUFFIX + '.csv'), 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
    json.dump({'population_by_source': dict(pop), 'sample_by_source': {g: dict(c) for g, c in tab.items()}, 'est_corrupted_share': est_c / N, 'est_notfound_share': est_nf / N, 'n': n_used}, open(os.path.join(ROOT, 'data', 'dataset', 'blind_autoverified_estimate' + SUFFIX + '.json'), 'w'), indent=1)
open(os.path.join(ROOT, 'data', 'dataset', 'blind_checks' + SUFFIX + '.md'), 'w').write('\n'.join(L) + '\n'); print('\n'.join(L))
