"""Search-channel analysis for NOT_FOUND decisions: which evidence channel each decision cites, the NOT_FOUND rate by
adjudication order (file order, a proxy for time), and blind second-adjudicator agreement on sampled NOT_FOUND decisions
by channel. Writes data/dataset/channel_analysis.md."""
import csv, collections, os
from urllib.parse import urlparse
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
rows = list(csv.DictReader(open(os.path.join(ROOT, 'data/adjudication/decisions.csv'))))
def channel(u):
    u = (u or '').lower()
    if not u: return 'none'
    if u.startswith('search:'): return 'search-note'
    h = urlparse(u).netloc
    for k, v in [('yahoo', 'yahoo'), ('google', 'google'), ('brave', 'brave'), ('bing', 'bing'), ('crossref', 'crossref'), ('arxiv', 'arxiv'), ('pubmed', 'pubmed'), ('doi.org', 'doi'), ('openlibrary', 'openlibrary'), ('archive.org', 'wayback'), ('semanticscholar', 's2')]:
        if k in h: return v
    return 'other-page'
L = ['# Search-channel analysis (auto-generated by code/channel_analysis.py)\n']
ch = collections.Counter(channel(r['evidence_url']) for r in rows); nf = collections.Counter(channel(r['evidence_url']) for r in rows if r['category'] in ('NOT_FOUND', 'WEB_RESOURCE_NOT_FOUND'))
L.append('- Evidence channel of all decisions: ' + ', '.join(f'{k} {v}' for k, v in ch.most_common()))
L.append('- Evidence channel of NOT_FOUND decisions: ' + ', '.join(f'{k} {v}' for k, v in nf.most_common()))
n = len(rows); parts = [rows[i * n // 3:(i + 1) * n // 3] for i in range(3)]
for i, t in enumerate(parts):
    k = sum(1 for r in t if r['category'] in ('NOT_FOUND', 'WEB_RESOURCE_NOT_FOUND')); a = sum(1 for r in t if r['category'] != 'UNADJUDICABLE')
    L.append(f'- Adjudication-order tercile {i+1}: NOT_FOUND {k}/{a} = {100*k/a:.1f}% of adjudicable decisions; channels: ' + ', '.join(f'{c} {v}' for c, v in collections.Counter(channel(r["evidence_url"]) for r in t).most_common(4)))
bp = os.path.join(ROOT, 'data/adjudication/blind/blind_manual_sample.csv')
if os.path.exists(bp):
    dec = {(r['number'], int(r['idx'])): r for r in rows}; by = collections.defaultdict(lambda: [0, 0])
    for b in csv.DictReader(open(bp)):
        if b['first'] != 'NOT_FOUND': continue
        num, idx = b['key'].split(':'); r = dec.get((num, int(idx))); c = channel(r['evidence_url']) if r else 'missing'
        by[c][1] += 1; by[c][0] += (b['blind'] == 'NOT_FOUND')
    L.append('- Blind agreement on sampled NOT_FOUND decisions by evidence channel (agree/total): ' + ', '.join(f'{c} {a}/{t}' for c, (a, t) in by.items()))
open(os.path.join(ROOT, 'data/dataset/channel_analysis.md'), 'w').write('\n'.join(L) + '\n'); print('\n'.join(L))
