"""Human-anchored validation: compare the human labels in data/adjudication/blind/human_coding_sheet.csv (columns
HUMAN_CATEGORY, HUMAN_NOTE) with the first adjudicator's label and the blind agent's label, overall and per stratum
(raw agreement and Cohen's kappa, for categories and for fabricated-vs-not). Writes data/dataset/human_agreement.md and
data/adjudication/blind/human_overrides.json (human labels for the automatically verified entries, used by
blind_checks.py when HUMAN_OVERRIDE=1)."""
import csv, os, json, collections
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
rows = [r for r in csv.DictReader(open(os.path.join(ROOT, 'data/adjudication/blind/human_coding_sheet.csv'))) if (r.get('HUMAN_CATEGORY') or '').strip()]
def col(c): c = (c or '').strip().upper(); return {'WEB_RESOURCE_EXISTS': 'EXISTS', 'WEB_RESOURCE_NOT_FOUND': 'NOT_FOUND', 'VERIFIED (AUTOMATED)': 'EXISTS'}.get(c, c)
def fab(c): return col(c) in ('NOT_FOUND', 'EXISTS_CORRUPTED')
def kappa(pairs):
    n = len(pairs)
    if not n: return float('nan'), float('nan')
    cats = sorted({a for a, _ in pairs} | {b for _, b in pairs}); po = sum(a == b for a, b in pairs) / n
    pe = sum((sum(a == c for a, _ in pairs) / n) * (sum(b == c for _, b in pairs) / n) for c in cats)
    return po, (po - pe) / (1 - pe) if pe < 1 else float('nan')
L = [f'# Human-coded validation ({len(rows)} items; auto-generated by code/human_agreement.py)\n']
L.append('Strata: ' + ', '.join(f'{k} {v}' for k, v in collections.Counter(r['stratum'] for r in rows).items()))
L.append('Human categories: ' + ', '.join(f'{k} {v}' for k, v in collections.Counter(col(r['HUMAN_CATEGORY']) for r in rows).items()) + '\n')
for label, key in [('first adjudicator (or automated VERIFIED)', 'label_first_adjudicator'), ('blind agent', 'label_blind_agent')]:
    for strat in ['all', 'manual (both strata)', 'manual-disputed', 'manual-agreed', 'automated (both strata)', 'auto-disputed', 'auto-agreed']:
        sel = [r for r in rows if strat == 'all' or (strat.startswith('manual (') and r['stratum'].startswith('manual')) or (strat.startswith('automated (') and r['stratum'].startswith('auto')) or r['stratum'] == strat]
        if not sel: continue
        pairs = [(col(r[key]), col(r['HUMAN_CATEGORY'])) for r in sel]
        po, k = kappa(pairs); po2, k2 = kappa([(fab(a), fab(b)) for a, b in pairs])
        L.append(f'- Human vs {label}, {strat} (n={len(sel)}): categories {100*po:.1f}% agreement (kappa {k:.2f}); fabricated-vs-not {100*po2:.1f}% (kappa {k2:.2f})')
    L.append('')
# where the human sided when the two agents disagreed
dis = [r for r in rows if r['stratum'] == 'manual-disputed']
side = collections.Counter('first' if col(r['HUMAN_CATEGORY']) == col(r['label_first_adjudicator']) else ('blind' if col(r['HUMAN_CATEGORY']) == col(r['label_blind_agent']) else 'neither') for r in dis)
L.append(f'- On the {len(dis)} manual decisions where the agents disagreed, the human agreed with the first adjudicator in {side["first"]}, with the blind agent in {side["blind"]}, with neither in {side["neither"]}')
autod = [r for r in rows if r['stratum'] == 'auto-disputed']
side2 = collections.Counter('blind (error confirmed)' if col(r['HUMAN_CATEGORY']) == col(r['label_blind_agent']) else ('automated (entry correct)' if col(r['HUMAN_CATEGORY']) == 'EXISTS' else 'other') for r in autod)
L.append(f'- On the {len(autod)} automated matches that the blind agent called corrupted or invented, the human confirmed the blind agent in {side2["blind (error confirmed)"]}, called the entry correctly cited in {side2["automated (entry correct)"]}, other {side2["other"]}')
L.append('\n## Human labels for the disputed automated matches\n')
for r in autod: L.append(f"- {r['item']} {r['key']}: blind agent {r['label_blind_agent']} -> human {r['HUMAN_CATEGORY']} ({(r.get('HUMAN_NOTE') or '')[:120]})")
open(os.path.join(ROOT, 'data/dataset/human_agreement.md'), 'w').write('\n'.join(L) + '\n')
json.dump({r['key']: r['HUMAN_CATEGORY'].strip().upper() for r in rows if r['stratum'].startswith('auto')}, open(os.path.join(ROOT, 'data/adjudication/blind/human_overrides.json'), 'w'), indent=1)
print('\n'.join(L))
